const Discord = require("discord.js");
const client = new Discord.Client();
const client2 = new Discord.Client();
const client3 = new Discord.Client();
const client4 = new Discord.Client();
const client5 = new Discord.Client();
const client6 = new Discord.Client();
const client7 = new Discord.Client();
const client8 = new Discord.Client();
const client9 = new Discord.Client();
const client10 = new Discord.Client();
const client11 = new Discord.Client();
const client12 = new Discord.Client();
const client13 = new Discord.Client();
const client14 = new Discord.Client();
const client15 = new Discord.Client();
const client16 = new Discord.Client();
const client17 = new Discord.Client();
const client18 = new Discord.Client();
const client19 = new Discord.Client();
const client20 = new Discord.Client();
const client21 = new Discord.Client();
const client22 = new Discord.Client();
const client23 = new Discord.Client();
const client24 = new Discord.Client();
const client25 = new Discord.Client();
const client26 = new Discord.Client();
const client27 = new Discord.Client();
const client28 = new Discord.Client();
const client29 = new Discord.Client();
const client30 = new Discord.Client();
const client31 = new Discord.Client();
const client32 = new Discord.Client();
const client33 = new Discord.Client();
const client34 = new Discord.Client();
const client35 = new Discord.Client();
const client36 = new Discord.Client();
const client37 = new Discord.Client();
const client38 = new Discord.Client();
const client39 = new Discord.Client();
const client40 = new Discord.Client();
const client41 = new Discord.Client();
const client42 = new Discord.Client();
const client43 = new Discord.Client();
const client45 = new Discord.Client();
const client46 = new Discord.Client();
const client47 = new Discord.Client();
const client48 = new Discord.Client();
const client49 = new Discord.Client();
const client50 = new Discord.Client();
const client51 = new Discord.Client();
const client52 = new Discord.Client();
const client53 = new Discord.Client();
const client54 = new Discord.Client();
const client55 = new Discord.Client();
const client56 = new Discord.Client();
const client57 = new Discord.Client();
const client58 = new Discord.Client();
const client59 = new Discord.Client();
const client60 = new Discord.Client();
const client61 = new Discord.Client();
const client62 = new Discord.Client();
const client63 = new Discord.Client();
const client64 = new Discord.Client();
const client65 = new Discord.Client();
const client66 = new Discord.Client();
const client67 = new Discord.Client();
const client68 = new Discord.Client();
const client69 = new Discord.Client();
const client70 = new Discord.Client();
const client71 = new Discord.Client();
const client72 = new Discord.Client();
const client73 = new Discord.Client();
const client74 = new Discord.Client();
const client75 = new Discord.Client();
const client76 = new Discord.Client();
const client77 = new Discord.Client();
const client78 = new Discord.Client();
const client79 = new Discord.Client();
const client80 = new Discord.Client();
const client81 = new Discord.Client();
const client82 = new Discord.Client();
const client83 = new Discord.Client();
const client84 = new Discord.Client();
const client85 = new Discord.Client();
const client86 = new Discord.Client();
const client87 = new Discord.Client();
const client88 = new Discord.Client();
const client89 = new Discord.Client();
const client90 = new Discord.Client();
const client91 = new Discord.Client();
const client92 = new Discord.Client();
const client93 = new Discord.Client();
const client94 = new Discord.Client();
const client95 = new Discord.Client();
const client96 = new Discord.Client();
const client97 = new Discord.Client();
const client98 = new Discord.Client();
const client99 = new Discord.Client();
const client100 = new Discord.Client();


client.on('message', msg => {
  if (msg.content === '#test') {
    msg.channel.send('Test Successful');
    msg.channel.sendFile('https://media.giphy.com/media/8GY3UiUjwKwhO/giphy.gif')
  }
});


client.login(process.env.USER_TOKEN); 
client2.login(process.env.USER_TOKEN); 
client3.login(process.env.USER_TOKEN); 
client4.login(process.env.USER_TOKEN); 
client5.login(process.env.USER_TOKEN);
client6.login(process.env.USER_TOKEN);
client7.login(process.env.USER_TOKEN);
client8.login(process.env.USER_TOKEN);
client9.login(process.env.USER_TOKEN);
client10.login(process.env.USER_TOKEN);
client11.login(process.env.USER_TOKEN);
client12.login(process.env.USER_TOKEN);
client13.login(process.env.USER_TOKEN);
client14.login(process.env.USER_TOKEN);
client15.login(process.env.USER_TOKEN);
client16.login(process.env.USER_TOKEN);
client17.login(process.env.USER_TOKEN);
client18.login(process.env.USER_TOKEN);
client19.login(process.env.USER_TOKEN);
client20.login(process.env.USER_TOKEN);
client21.login(process.env.USER_TOKEN);
client22.login(process.env.USER_TOKEN);
client23.login(process.env.USER_TOKEN);
client24.login(process.env.USER_TOKEN);
client25.login(process.env.USER_TOKEN);
client26.login(process.env.USER_TOKEN);
client27.login(process.env.USER_TOKEN);
client28.login(process.env.USER_TOKEN);
client29.login(process.env.USER_TOKEN);
client30.login(process.env.USER_TOKEN);
client31.login(process.env.USER_TOKEN);
client32.login(process.env.USER_TOKEN);
client33.login(process.env.USER_TOKEN);
client34.login(process.env.USER_TOKEN);
client35.login(process.env.USER_TOKEN);
client36.login(process.env.USER_TOKEN);
client37.login(process.env.USER_TOKEN);
client38.login(process.env.USER_TOKEN);
client39.login(process.env.USER_TOKEN);
client40.login(process.env.USER_TOKEN);
client41.login(process.env.USER_TOKEN);
client42.login(process.env.USER_TOKEN);
client43.login(process.env.USER_TOKEN);
client44.login(process.env.USER_TOKEN);
client45.login(process.env.USER_TOKEN);
client46.login(process.env.USER_TOKEN);
client47.login(process.env.USER_TOKEN);
client48.login(process.env.USER_TOKEN);
client49.login(process.env.USER_TOKEN);
client50.login(process.env.USER_TOKEN);
client51.login(process.env.USER_TOKEN);
client52.login(process.env.USER_TOKEN);
client53.login(process.env.USER_TOKEN);
client54.login(process.env.USER_TOKEN);
client55.login(process.env.USER_TOKEN);
client56.login(process.env.USER_TOKEN);
client57.login(process.env.USER_TOKEN);
client58.login(process.env.USER_TOKEN);
client59.login(process.env.USER_TOKEN);
client60.login(process.env.USER_TOKEN);
client61.login(process.env.USER_TOKEN);
client62.login(process.env.USER_TOKEN);
client63.login(process.env.USER_TOKEN);
client64.login(process.env.USER_TOKEN);
client65.login(process.env.USER_TOKEN);
client66.login(process.env.USER_TOKEN);
client67.login(process.env.USER_TOKEN);
client68.login(process.env.USER_TOKEN);
client69.login(process.env.USER_TOKEN);
client70.login(process.env.USER_TOKEN);
client71.login(process.env.USER_TOKEN);
client72.login(process.env.USER_TOKEN);
client73.login(process.env.USER_TOKEN);
client74.login(process.env.USER_TOKEN);
client75.login(process.env.USER_TOKEN);
client76.login(process.env.USER_TOKEN);
client77.login(process.env.USER_TOKEN);
client78.login(process.env.USER_TOKEN);
client79.login(process.env.USER_TOKEN);
client80.login(process.env.USER_TOKEN);
client81.login(process.env.USER_TOKEN);
client82.login(process.env.USER_TOKEN);
client83.login(process.env.USER_TOKEN);
client84.login(process.env.USER_TOKEN);
client85.login(process.env.USER_TOKEN);
client86.login(process.env.USER_TOKEN);
client87.login(process.env.USER_TOKEN);
client88.login(process.env.USER_TOKEN);
client89.login(process.env.USER_TOKEN);
client90.login(process.env.USER_TOKEN);
client91.login(process.env.USER_TOKEN);
client92.login(process.env.USER_TOKEN);
client93.login(process.env.USER_TOKEN);
client94.login(process.env.USER_TOKEN);
client95.login(process.env.USER_TOKEN);
client96.login(process.env.USER_TOKEN);
client97.login(process.env.USER_TOKEN);
client98.login(process.env.USER_TOKEN);
client99.login(process.env.USER_TOKEN);
client100.login(process.env.USER_TOKEN);